apiVersion: v2
name: syncoor-web
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: syncoor-web
    repository: https://ethpandaops.github.io/ethereum-helm-charts
    version: 0.0.1
